#ifndef ENMYPLAN_H
#define ENMYPLAN_H

struct ENMYPLAN_73fake // hashcode: 0x83FC5E62 (dec: -2080612766)
{
	unsigned long (*function)(); // size=0, offset=0 //  hashcode: 0x95171AC1 (dec: -1793647935), parent name: 'ENMYPLAN_73fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *fnData;				 // size=0, offset=4 //  hashcode: 0x1E2468BA (dec: 505702586), parent name: 'ENMYPLAN_73fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_74fake // hashcode: 0xEF1915EC (dec: -283568660)
{
	struct _G2SVector3_Type base;   // size=6, offset=0 //  hashcode: 0xA6498E4F (dec: -1505128881), parent name: 'ENMYPLAN_74fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2SVector3_Type offset; // size=6, offset=6 //  hashcode: 0xB959A5C9 (dec: -1185307191), parent name: 'ENMYPLAN_74fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_75fake // hashcode: 0xF09526F2 (dec: -258660622)
{
	struct _G2Quat_Type src;  // size=8, offset=0 //  hashcode: 0x367FBCD8 (dec: 914341080), parent name: 'ENMYPLAN_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2Quat_Type dest; // size=8, offset=8 //  hashcode: 0x4CCA25A6 (dec: 1288316326), parent name: 'ENMYPLAN_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union ENMYPLAN_76fake // Hashcode: 0xB9153BA5 (dec: -1189790811)
{
	struct ENMYPLAN_73fake callback; // size=8, offset=0
	struct ENMYPLAN_74fake vector;   // size=12, offset=0
	struct ENMYPLAN_75fake quat;	 // size=16, offset=0
};

union ENMYPLAN_77fake // Hashcode: 0x3C88A9DD (dec: 1015589341)
{
	long color;				// size=0, offset=0
	struct _RGBAColor rgba; // size=4, offset=0
};

union ENMYPLAN_78fake // Hashcode: 0x7D91CA1A (dec: 2106706458)
{
	long l;		// size=0, offset=0
	short s[2]; // size=4, offset=0
	char c[4];  // size=4, offset=0
};

struct ENMYPLAN_79fake // hashcode: 0xEE3A68BD (dec: -298161987)
{
	union ENMYPLAN_78fake size; // size=4, offset=0 //  hashcode: 0xA87794A6 (dec: -1468558170), parent name: 'ENMYPLAN_79fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_80fake // hashcode: 0x71C6D27A (dec: 1908855418)
{
	short x;				// size=0, offset=0 //  hashcode: 0xAEE3B1B7 (dec: -1360809545), parent name: 'ENMYPLAN_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;				// size=0, offset=2 //  hashcode: 0x922A9C9C (dec: -1842701156), parent name: 'ENMYPLAN_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;				// size=0, offset=4 //  hashcode: 0x472D8D90 (dec: 1194167696), parent name: 'ENMYPLAN_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zrot;				// size=0, offset=6 //  hashcode: 0xEDA249C0 (dec: -308131392), parent name: 'ENMYPLAN_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector offset; // size=8, offset=8 //  hashcode: 0x07ADD50C (dec: 128832780), parent name: 'ENMYPLAN_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_81fake // hashcode: 0x75EB506E (dec: 1978355822)
{
	long index; // size=0, offset=0 //  hashcode: 0xA7289B78 (dec: -1490510984), parent name: 'ENMYPLAN_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0xCE896298 (dec: -829857128), parent name: 'ENMYPLAN_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_82fake // hashcode: 0xC335D333 (dec: -1019882701)
{
	long index; // size=0, offset=0 //  hashcode: 0x57D477C1 (dec: 1473542081), parent name: 'ENMYPLAN_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0x892C002E (dec: -1993605074), parent name: 'ENMYPLAN_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_83fake // hashcode: 0xE8BE5996 (dec: -390178410)
{
	long index; // size=0, offset=0 //  hashcode: 0x72E13C1A (dec: 1927363610), parent name: 'ENMYPLAN_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0x453E3E14 (dec: 1161707028), parent name: 'ENMYPLAN_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_84fake // hashcode: 0x67A5E244 (dec: 1738924612)
{
	long time;  // size=0, offset=0 //  hashcode: 0x847B2E36 (dec: -2072302026), parent name: 'ENMYPLAN_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long scale; // size=0, offset=4 //  hashcode: 0x7C20B7D0 (dec: 2082518992), parent name: 'ENMYPLAN_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_85fake // hashcode: 0x88B7E633 (dec: -2001213901)
{
	long action;   // size=0, offset=0 //  hashcode: 0xF6FC3B14 (dec: -151241964), parent name: 'ENMYPLAN_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value[2]; // size=8, offset=4 //  hashcode: 0xD87C1D12 (dec: -662954734), parent name: 'ENMYPLAN_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_86fake // hashcode: 0xF22DC2FC (dec: -231881988)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x8355F75C (dec: -2091518116), parent name: 'ENMYPLAN_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *data;  // size=0, offset=4 //  hashcode: 0xBC8B01C7 (dec: -1131740729), parent name: 'ENMYPLAN_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_87fake // hashcode: 0x779A8640 (dec: 2006615616)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x87657E0C (dec: -2023391732), parent name: 'ENMYPLAN_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long frame;  // size=0, offset=4 //  hashcode: 0x6F0589CE (dec: 1862633934), parent name: 'ENMYPLAN_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_88fake // hashcode: 0xD23DB328 (dec: -767708376)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x72899037 (dec: 1921617975), parent name: 'ENMYPLAN_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long model;  // size=0, offset=4 //  hashcode: 0xB798B953 (dec: -1214727853), parent name: 'ENMYPLAN_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_89fake // hashcode: 0xDD9FF511 (dec: -576719599)
{
	unsigned char target;	 // size=0, offset=0 //  hashcode: 0x71EF59A2 (dec: 1911511458), parent name: 'ENMYPLAN_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source1;	// size=0, offset=1 //  hashcode: 0xBE5AC9AF (dec: -1101346385), parent name: 'ENMYPLAN_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source2;	// size=0, offset=2 //  hashcode: 0x1BEBD4EA (dec: 468440298), parent name: 'ENMYPLAN_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad;		  // size=0, offset=3 //  hashcode: 0x5EFFAA10 (dec: 1593813520), parent name: 'ENMYPLAN_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0x4B426D98 (dec: 1262644632), parent name: 'ENMYPLAN_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_90fake // hashcode: 0x123DEADE (dec: 306047710)
{
	long timer;  // size=0, offset=0 //  hashcode: 0x8ECFA62F (dec: -1898994129), parent name: 'ENMYPLAN_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long action; // size=0, offset=4 //  hashcode: 0x23CDF745 (dec: 600700741), parent name: 'ENMYPLAN_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_91fake // hashcode: 0x4B8174A1 (dec: 1266775201)
{
	short index;					// size=0, offset=0 //  hashcode: 0x7AF14F5D (dec: 2062634845), parent name: 'ENMYPLAN_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;						// size=0, offset=2 //  hashcode: 0xA58C94C3 (dec: -1517513533), parent name: 'ENMYPLAN_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *upSignal;   // size=0, offset=4 //  hashcode: 0xB715E3F4 (dec: -1223302156), parent name: 'ENMYPLAN_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *downSignal; // size=0, offset=8 //  hashcode: 0x357FB405 (dec: 897561605), parent name: 'ENMYPLAN_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_92fake // hashcode: 0x58E6A2BC (dec: 1491509948)
{
	long currentnum; // size=0, offset=0 //  hashcode: 0xF63BD70A (dec: -163850486), parent name: 'ENMYPLAN_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long streamID;   // size=0, offset=4 //  hashcode: 0x3EA611FE (dec: 1051070974), parent name: 'ENMYPLAN_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char toname[16]; // size=16, offset=8 //  hashcode: 0x2189F13C (dec: 562688316), parent name: 'ENMYPLAN_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_93fake // hashcode: 0x94FF9F16 (dec: -1795186922)
{
	char num;			   // size=0, offset=0 //  hashcode: 0x44CE2269 (dec: 1154359913), parent name: 'ENMYPLAN_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char vel;			   // size=0, offset=1 //  hashcode: 0x93F362FE (dec: -1812765954), parent name: 'ENMYPLAN_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short misc;			   // size=0, offset=2 //  hashcode: 0x51101291 (dec: 1360007825), parent name: 'ENMYPLAN_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char flags;			   // size=0, offset=4 //  hashcode: 0x9E81E0EC (dec: -1635655444), parent name: 'ENMYPLAN_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char timeToLive;	   // size=0, offset=5 //  hashcode: 0xC82D7F1E (dec: -936542434), parent name: 'ENMYPLAN_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short dummy2;		   // size=0, offset=6 //  hashcode: 0xA19C4EAD (dec: -1583591763), parent name: 'ENMYPLAN_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Object *object; // size=0, offset=8 //  hashcode: 0x58A3A0F6 (dec: 1487118582), parent name: 'ENMYPLAN_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_94fake // hashcode: 0xDCFD5251 (dec: -587378095)
{
	long index;  // size=0, offset=0 //  hashcode: 0x4B407122 (dec: 1262514466), parent name: 'ENMYPLAN_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0xF60E3551 (dec: -166841007), parent name: 'ENMYPLAN_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_95fake // hashcode: 0x5ABB10DC (dec: 1522208988)
{
	short type; // size=0, offset=0 //  hashcode: 0xC4848DA9 (dec: -997945943), parent name: 'ENMYPLAN_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time; // size=0, offset=2 //  hashcode: 0xDB255501 (dec: -618310399), parent name: 'ENMYPLAN_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_96fake // hashcode: 0x7E856C19 (dec: 2122673177)
{
	long time;   // size=0, offset=0 //  hashcode: 0x729C69C2 (dec: 1922853314), parent name: 'ENMYPLAN_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0xCC5CDCAA (dec: -866329430), parent name: 'ENMYPLAN_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_97fake // hashcode: 0x69EC9C53 (dec: 1777114195)
{
	void *intro;			  // size=0, offset=0 //  hashcode: 0x2B593973 (dec: 727267699), parent name: 'ENMYPLAN_97fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0x0118BD76 (dec: 18398582), parent name: 'ENMYPLAN_97fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_98fake // hashcode: 0x378083E9 (dec: 931169257)
{
	char world[9]; // size=9, offset=0 //  hashcode: 0xE2911939 (dec: -493807303), parent name: 'ENMYPLAN_98fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char level[9]; // size=9, offset=9 //  hashcode: 0x613330DC (dec: 1630744796), parent name: 'ENMYPLAN_98fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_99fake // hashcode: 0xF2779FB2 (dec: -227041358)
{
	struct Signal *signal; // size=0, offset=0 //  hashcode: 0x1601C34D (dec: 369214285), parent name: 'ENMYPLAN_99fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long times;			   // size=0, offset=4 //  hashcode: 0x45137754 (dec: 1158903636), parent name: 'ENMYPLAN_99fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_100fake // hashcode: 0x92F223D8 (dec: -1829624872)
{
	unsigned char r;   // size=0, offset=0 //  hashcode: 0xA91AB2B6 (dec: -1457868106), parent name: 'ENMYPLAN_100fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char g;   // size=0, offset=1 //  hashcode: 0x755C60E9 (dec: 1968988393), parent name: 'ENMYPLAN_100fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char b;   // size=0, offset=2 //  hashcode: 0x04378D77 (dec: 70749559), parent name: 'ENMYPLAN_100fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad; // size=0, offset=3 //  hashcode: 0xCF8542FC (dec: -813350148), parent name: 'ENMYPLAN_100fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_101fake // hashcode: 0xCE431BF4 (dec: -834462732)
{
	short x;	 // size=0, offset=0 //  hashcode: 0xF17296C6 (dec: -244148538), parent name: 'ENMYPLAN_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;	 // size=0, offset=2 //  hashcode: 0xB92F9474 (dec: -1188064140), parent name: 'ENMYPLAN_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time;  // size=0, offset=4 //  hashcode: 0x2FAA0DD5 (dec: 799673813), parent name: 'ENMYPLAN_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short index; // size=0, offset=6 //  hashcode: 0x2E67DA8A (dec: 778558090), parent name: 'ENMYPLAN_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char *text;  // size=0, offset=8 //  hashcode: 0x1E2E839D (dec: 506364829), parent name: 'ENMYPLAN_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union ENMYPLAN_102fake // Hashcode: 0x27DE167F (dec: 668866175)
{
	struct ENMYPLAN_79fake misc[3];		 // size=12, offset=0
	struct _CameraKey *cameraKey;		 // size=24, offset=0
	struct ENMYPLAN_80fake teleport;	 // size=16, offset=0
	struct ENMYPLAN_81fake cameraValue;  // size=8, offset=0
	struct ENMYPLAN_82fake miscValue;	// size=8, offset=0
	struct ENMYPLAN_83fake logicValue;   // size=8, offset=0
	long timer;							 // size=0, offset=0
	long times;							 // size=0, offset=0
	long lightGroup;					 // size=0, offset=0
	long farPlane;						 // size=0, offset=0
	long cameraAdjust;					 // size=0, offset=0
	long cameraMode;					 // size=0, offset=0
	long cameraLock;					 // size=0, offset=0
	long cameraUnlock;					 // size=0, offset=0
	long cameraSmooth;					 // size=0, offset=0
	long cameraTimer;					 // size=0, offset=0
	struct ENMYPLAN_84fake cameraShake;  // size=8, offset=0
	long cameraSave;					 // size=0, offset=0
	long cameraRestore;					 // size=0, offset=0
	struct _BGObject *bgObject;			 // size=24, offset=0
	long value[2];						 // size=8, offset=0
	struct ENMYPLAN_85fake sound;		 // size=12, offset=0
	void *intro;						 // size=0, offset=0
	long deathZ;						 // size=0, offset=0
	struct ENMYPLAN_86fake dsignal;		 // size=8, offset=0
	void *mirror;						 // size=0, offset=0
	long fogNear;						 // size=0, offset=0
	long fogFar;						 // size=0, offset=0
	struct ENMYPLAN_87fake gotoFrame;	// size=8, offset=0
	struct ENMYPLAN_88fake changeModel;  // size=8, offset=0
	void *vmObject;						 // size=0, offset=0
	struct ENMYPLAN_89fake logic;		 // size=8, offset=0
	void *callSignal;					 // size=0, offset=0
	struct _SVector offset;				 // size=8, offset=0
	struct Signal *gotoLabel;			 // size=0, offset=0
	struct Signal *gosubLabel;			 // size=0, offset=0
	struct ENMYPLAN_90fake control;		 // size=8, offset=0
	struct ENMYPLAN_91fake zSignal;		 // size=12, offset=0
	struct ENMYPLAN_92fake StreamLevel;  // size=24, offset=0
	struct ENMYPLAN_93fake shards;		 // size=12, offset=0
	struct ENMYPLAN_94fake cameraSpline; // size=8, offset=0
	struct ENMYPLAN_95fake screenWipe;   // size=4, offset=0
	long voiceSitId;					 // size=0, offset=0
	struct ENMYPLAN_96fake introFX;		 // size=8, offset=0
	struct ENMYPLAN_97fake introActive;  // size=8, offset=0
	struct ENMYPLAN_98fake levelChange;  // size=18, offset=0
	long blendStart;					 // size=0, offset=0
	struct ENMYPLAN_99fake setTimes;	 // size=8, offset=0
	struct ENMYPLAN_100fake color;		 // size=4, offset=0
	struct ENMYPLAN_101fake print;		 // size=12, offset=0
	long slideAngle;					 // size=0, offset=0
};

union ENMYPLAN_103fake // Hashcode: 0x79A288F7 (dec: 2040695031)
{
	struct _HSphere *hsphere; // size=20, offset=0
	struct _HBox *hbox;		  // size=28, offset=0
	struct _HFace *hface;	 // size=12, offset=0
};

union ENMYPLAN_108fake // Hashcode: 0xEC18B7AC (dec: -333924436)
{
	struct _VMOffset moveOffsets;		// size=6, offset=0
	struct _VMColorOffset colorOffsets; // size=3, offset=0
};

struct ENMYPLAN_110fake // hashcode: 0x6590E1C6 (dec: 1703993798)
{
	struct MultiSpline *posSpline;	// size=0, offset=0 //  hashcode: 0x3E57DA19 (dec: 1045944857), parent name: 'ENMYPLAN_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSpline *targetSpline; // size=0, offset=4 //  hashcode: 0x4D869736 (dec: 1300666166), parent name: 'ENMYPLAN_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector lastSplinePos;	// size=8, offset=8 //  hashcode: 0x7DE6C8A8 (dec: 2112276648), parent name: 'ENMYPLAN_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short splinePointAhead;			  // size=0, offset=16 //  hashcode: 0x7B010CE3 (dec: 2063666403), parent name: 'ENMYPLAN_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short cinema_done;				  // size=0, offset=18 //  hashcode: 0x8F041772 (dec: -1895557262), parent name: 'ENMYPLAN_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	int splinecam_currkey;			  // size=0, offset=20 //  hashcode: 0xAE765546 (dec: -1367976634), parent name: 'ENMYPLAN_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	int splinecam_helpkey;			  // size=0, offset=24 //  hashcode: 0xB09D4AA6 (dec: -1331869018), parent name: 'ENMYPLAN_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_111fake // hashcode: 0x2F208608 (dec: 790660616)
{
	struct _Position offset;   // size=6, offset=0 //  hashcode: 0x53FD9562 (dec: 1409127778), parent name: 'ENMYPLAN_111fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _Rotation rotation; // size=8, offset=6 //  hashcode: 0xFB4F2DD8 (dec: -78697000), parent name: 'ENMYPLAN_111fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long focusDistance;		   // size=0, offset=16 //  hashcode: 0xCC0D551C (dec: -871541476), parent name: 'ENMYPLAN_111fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_112fake // hashcode: 0x7669B588 (dec: 1986639240)
{
	struct _TFace *tface;				 // size=12, offset=0 //  hashcode: 0x830F13D2 (dec: -2096163886), parent name: 'ENMYPLAN_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *oldTFace;			 // size=12, offset=4 //  hashcode: 0x9EA19F3E (dec: -1633575106), parent name: 'ENMYPLAN_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector oldTargetRot;		 // size=8, offset=8 //  hashcode: 0xD4C6866E (dec: -725186962), parent name: 'ENMYPLAN_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long timer;							 // size=0, offset=16 //  hashcode: 0x3A2A5424 (dec: 975852580), parent name: 'ENMYPLAN_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector oldFocusInstancePos; // size=8, offset=20 //  hashcode: 0x7F2219E4 (dec: 2132941284), parent name: 'ENMYPLAN_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_113fake // hashcode: 0x6704F023 (dec: 1728376867)
{
	long stopTimer;			 // size=0, offset=0 //  hashcode: 0x9D261D5E (dec: -1658446498), parent name: 'ENMYPLAN_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long stopHit;			 // size=0, offset=4 //  hashcode: 0x8F4E113E (dec: -1890709186), parent name: 'ENMYPLAN_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *tface;	// size=12, offset=8 //  hashcode: 0x044393EE (dec: 71537646), parent name: 'ENMYPLAN_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *oldTFace; // size=12, offset=12 //  hashcode: 0xCD59FFBD (dec: -849739843), parent name: 'ENMYPLAN_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long hit;				 // size=0, offset=16 //  hashcode: 0x4D259930 (dec: 1294309680), parent name: 'ENMYPLAN_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_114fake // hashcode: 0xA6FD1322 (dec: -1493363934)
{
	struct ENMYPLAN_110fake Cinematic; // size=28, offset=0 //  hashcode: 0x1E9C5743 (dec: 513562435), parent name: 'ENMYPLAN_114fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct ENMYPLAN_111fake Idle;	  // size=20, offset=28 //  hashcode: 0xD5E5BC4D (dec: -706364339), parent name: 'ENMYPLAN_114fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct ENMYPLAN_112fake Behind;	// size=28, offset=48 //  hashcode: 0x683E7392 (dec: 1748923282), parent name: 'ENMYPLAN_114fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct ENMYPLAN_113fake Follow;	// size=20, offset=76 //  hashcode: 0x86AB44BE (dec: -2035596098), parent name: 'ENMYPLAN_114fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_181fake // hashcode: 0x2403A112 (dec: 604217618)
{
	struct _Instance *parent; // size=616, offset=0 //  hashcode: 0x4E880E3B (dec: 1317539387), parent name: 'ENMYPLAN_181fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long segment;			  // size=0, offset=4 //  hashcode: 0x964A66D9 (dec: -1773508903), parent name: 'ENMYPLAN_181fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct ENMYPLAN_182fake // hashcode: 0x431DF168 (dec: 1126035816)
{
	short xVel;  // size=0, offset=0 //  hashcode: 0x84C8C9B9 (dec: -2067215943), parent name: 'ENMYPLAN_182fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short yVel;  // size=0, offset=2 //  hashcode: 0x7F7566B2 (dec: 2138400434), parent name: 'ENMYPLAN_182fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zVel;  // size=0, offset=4 //  hashcode: 0x78242ACA (dec: 2015636170), parent name: 'ENMYPLAN_182fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short xAccl; // size=0, offset=6 //  hashcode: 0x24ABC1CD (dec: 615236045), parent name: 'ENMYPLAN_182fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short yAccl; // size=0, offset=8 //  hashcode: 0x870EBEE3 (dec: -2029076765), parent name: 'ENMYPLAN_182fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zAccl; // size=0, offset=10 //  hashcode: 0x83660E09 (dec: -2090463735), parent name: 'ENMYPLAN_182fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union ENMYPLAN_183fake // Hashcode: 0xB7A2DAAA (dec: -1214063958)
{
	struct ENMYPLAN_181fake flame; // size=8, offset=0
	struct ENMYPLAN_182fake phys;  // size=12, offset=0
};

union ENMYPLAN_216fake // Hashcode: 0xDAEB41F2 (dec: -622116366)
{
	struct _Instance *target;	 // size=616, offset=0
	struct _Position position;	// size=6, offset=0
	struct _Rotation direction;   // size=8, offset=0
	struct _Position throwVector; // size=6, offset=0
};

struct EnemyPlanSlotData // hashcode: 0xA348D4B1 (dec: -1555508047)
{
	char slotInUse;					// size=0, offset=0 //  hashcode: 0x8AA36C35 (dec: -1969001419), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
	char state;						// size=0, offset=1 //  hashcode: 0xF49DE88A (dec: -190977910), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
	char wayPointBeingServoedTo;	// size=0, offset=2 //  hashcode: 0xED2C4C64 (dec: -315863964), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _Position startPos;		// size=6, offset=4 //  hashcode: 0x66719914 (dec: 1718720788), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _Position goalPos;		// size=6, offset=10 //  hashcode: 0x063875D1 (dec: 104363473), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _Position oldCurrentPos; // size=6, offset=16 //  hashcode: 0xE412310B (dec: -468569845), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct EnemyPlanData planData;  // size=68, offset=22 //  hashcode: 0x73EFAC09 (dec: 1945086985), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
	char targetType;				// size=0, offset=90 //  hashcode: 0x86C9C87C (dec: -2033596292), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
	short timer;					// size=0, offset=92 //  hashcode: 0x8EDC2DFB (dec: -1898172933), parent name: 'EnemyPlanSlotData', parent hashcode: 0xFFFFFFFF (dec: -1)
};

typedef struct EnemyPlanSlotData EnemyPlanSlotData;

extern void ENMYPLAN_InitEnemyPlanPool(void *enemyPlanPool); // 0x800965A4

extern int ENMYPLAN_GetNextAvailablePlanningSlot(); // 0x800965C4

extern int ENMYPLAN_GetInitializedPlanningWorkspaceFinal(); // 0x80096604

extern void ENMYPLAN_ReleasePlanningWorkspace(int slotID); // 0x80096660

extern int ENMYPLAN_WayPointSkipped(struct _Position *currentPos, struct _Position *targetPos, struct _Position *nextTargetPos); // 0x800966C8

extern int ENMYPLAN_WayPointReached(struct _Position *currentPos, struct _Position *oldCurrentPos, struct _Position *targetPos); // 0x80096834

extern void ENMYPLAN_Replan(struct EnemyPlanSlotData *planSlot); // 0x800968E4

extern int ENMYPLAN_PathClear(struct _Position *pos, struct _Position *target); // 0x80096910

extern int ENMYPLAN_MoveToTargetFinal(struct _Instance *instance, struct _Position *outputPos, int slotID, struct _Position *targetPos, int validNodeTypes); // 0x80096A90

extern int ValidSlotAndState(struct EnemyPlanSlotData *pool, int slotID); // 0x80096F9C

extern int ENMYPLAN_GetNodeTypeOfNextWaypoint(int slotID); // 0x80096FE0

extern int ENMYPLAN_GetPosOfNextWaypoint(int slotID, struct _Position *pos); // 0x8009704C

extern void ENMYPLAN_RelocatePlanPositions(int slotID, struct _Position *offset); // 0x800970EC

#endif
