#ifndef SNMAIN_H
#define SNMAIN_H

extern void __SN_ENTRY_POINT();

extern void __main();

extern void __initialised();

extern void __heapbase();

extern void __heapsize();

extern void __text();

extern void __textlen();

extern void __data();

extern void __datalen();

extern void __bss();

extern void __bsslen();

extern void the_cine_table();

extern void __ra_temp();

extern void voiceTracker();

#endif
