#ifndef SNMAIN_H
#define SNMAIN_H


extern void __SN_ENTRY_POINT() ; // 0x800B0E9C

extern void __main() ; // 0x800B0F44

extern void __initialised() ; // 0x800C5E1C

extern void __heapbase() ; // 0x800C5E20

extern void __heapsize() ; // 0x800C5E24

extern void __text() ; // 0x800C5E28

extern void __textlen() ; // 0x800C5E2C

extern void __data() ; // 0x800C5E30

extern void __datalen() ; // 0x800C5E34

extern void __bss() ; // 0x800C5E38

extern void __bsslen() ; // 0x800C5E3C

extern void the_cine_table() ; // 0x800C5E40

extern void __ra_temp() ; // 0x800D5E48

extern void voiceTracker() ; // 0x800D5E4C


#endif
