#ifndef GENERIC_H
#define GENERIC_H

struct GENERIC_73fake // hashcode: 0x81A7436C (dec: -2119744660)
{
	unsigned long (*function)(); // size=0, offset=0 //  hashcode: 0x363AC7EE (dec: 909821934), parent name: 'GENERIC_73fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *fnData;				 // size=0, offset=4 //  hashcode: 0x385F3E66 (dec: 945765990), parent name: 'GENERIC_73fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_74fake // hashcode: 0x7411CA84 (dec: 1947323012)
{
	struct _G2SVector3_Type base;   // size=6, offset=0 //  hashcode: 0xF788B239 (dec: -142036423), parent name: 'GENERIC_74fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2SVector3_Type offset; // size=6, offset=6 //  hashcode: 0x907874E9 (dec: -1871153943), parent name: 'GENERIC_74fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_75fake // hashcode: 0x569CFB73 (dec: 1453128563)
{
	struct _G2Quat_Type src;  // size=8, offset=0 //  hashcode: 0x2854C4AA (dec: 676644010), parent name: 'GENERIC_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2Quat_Type dest; // size=8, offset=8 //  hashcode: 0xB455F9E3 (dec: -1269433885), parent name: 'GENERIC_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union GENERIC_76fake // Hashcode: 0x55C9A583 (dec: 1439278467)
{
	struct GENERIC_73fake callback; // size=8, offset=0
	struct GENERIC_74fake vector;   // size=12, offset=0
	struct GENERIC_75fake quat;		// size=16, offset=0
};

union GENERIC_77fake // Hashcode: 0x95D27D31 (dec: -1781367503)
{
	long color;				// size=0, offset=0
	struct _RGBAColor rgba; // size=4, offset=0
};

union GENERIC_78fake // Hashcode: 0x93F5F1AC (dec: -1812598356)
{
	long l;		// size=0, offset=0
	short s[2]; // size=4, offset=0
	char c[4];  // size=4, offset=0
};

struct GENERIC_79fake // hashcode: 0x723A0A7D (dec: 1916406397)
{
	union GENERIC_78fake size; // size=4, offset=0 //  hashcode: 0x6C49316F (dec: 1816736111), parent name: 'GENERIC_79fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_80fake // hashcode: 0x126528A2 (dec: 308619426)
{
	short x;				// size=0, offset=0 //  hashcode: 0xCA5E01AD (dec: -899808851), parent name: 'GENERIC_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;				// size=0, offset=2 //  hashcode: 0x516D7052 (dec: 1366126674), parent name: 'GENERIC_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;				// size=0, offset=4 //  hashcode: 0xBD6C5215 (dec: -1116974571), parent name: 'GENERIC_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zrot;				// size=0, offset=6 //  hashcode: 0x03AA207E (dec: 61481086), parent name: 'GENERIC_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector offset; // size=8, offset=8 //  hashcode: 0x2B85C257 (dec: 730186327), parent name: 'GENERIC_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_81fake // hashcode: 0x6A656828 (dec: 1785030696)
{
	long index; // size=0, offset=0 //  hashcode: 0x5BE90B55 (dec: 1541999445), parent name: 'GENERIC_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0x8BE8C972 (dec: -1947678350), parent name: 'GENERIC_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_82fake // hashcode: 0xE2CC908C (dec: -489910132)
{
	long index; // size=0, offset=0 //  hashcode: 0x86A8A6B9 (dec: -2035767623), parent name: 'GENERIC_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0xAB8C8258 (dec: -1416854952), parent name: 'GENERIC_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_83fake // hashcode: 0x03EA94BD (dec: 65705149)
{
	long index; // size=0, offset=0 //  hashcode: 0x7B0A9A19 (dec: 2064292377), parent name: 'GENERIC_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0x65A6E15F (dec: 1705435487), parent name: 'GENERIC_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_84fake // hashcode: 0x09AB785A (dec: 162232410)
{
	long time;  // size=0, offset=0 //  hashcode: 0x8AD8F084 (dec: -1965494140), parent name: 'GENERIC_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long scale; // size=0, offset=4 //  hashcode: 0x797CD455 (dec: 2038223957), parent name: 'GENERIC_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_85fake // hashcode: 0xED38200E (dec: -315088882)
{
	long action;   // size=0, offset=0 //  hashcode: 0x1FA8A954 (dec: 531147092), parent name: 'GENERIC_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value[2]; // size=8, offset=4 //  hashcode: 0x54B29924 (dec: 1420990756), parent name: 'GENERIC_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_86fake // hashcode: 0xA957A2FB (dec: -1453874437)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x54D18FB4 (dec: 1423019956), parent name: 'GENERIC_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *data;  // size=0, offset=4 //  hashcode: 0x9A3F3116 (dec: -1707134698), parent name: 'GENERIC_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_87fake // hashcode: 0x17FF1D7E (dec: 402595198)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x73D26884 (dec: 1943169156), parent name: 'GENERIC_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long frame;  // size=0, offset=4 //  hashcode: 0x1CE5884E (dec: 484804686), parent name: 'GENERIC_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_88fake // hashcode: 0x4D53BB24 (dec: 1297333028)
{
	void *intro; // size=0, offset=0 //  hashcode: 0xCACC0DFD (dec: -892596739), parent name: 'GENERIC_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long model;  // size=0, offset=4 //  hashcode: 0x97511267 (dec: -1756294553), parent name: 'GENERIC_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_89fake // hashcode: 0x94CB6D95 (dec: -1798607467)
{
	unsigned char target;	 // size=0, offset=0 //  hashcode: 0x33816F65 (dec: 864120677), parent name: 'GENERIC_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source1;	// size=0, offset=1 //  hashcode: 0xE084575C (dec: -528197796), parent name: 'GENERIC_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source2;	// size=0, offset=2 //  hashcode: 0x4B6A8C02 (dec: 1265273858), parent name: 'GENERIC_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad;		  // size=0, offset=3 //  hashcode: 0x6FCD8875 (dec: 1875740789), parent name: 'GENERIC_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0x112E9981 (dec: 288266625), parent name: 'GENERIC_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_90fake // hashcode: 0xE6F8A3A1 (dec: -419912799)
{
	long timer;  // size=0, offset=0 //  hashcode: 0xE6A14C6F (dec: -425636753), parent name: 'GENERIC_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long action; // size=0, offset=4 //  hashcode: 0x4FF0B8A3 (dec: 1341175971), parent name: 'GENERIC_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_91fake // hashcode: 0x5B0A1B49 (dec: 1527389001)
{
	short index;					// size=0, offset=0 //  hashcode: 0x878DB62D (dec: -2020755923), parent name: 'GENERIC_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;						// size=0, offset=2 //  hashcode: 0xF2338409 (dec: -231504887), parent name: 'GENERIC_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *upSignal;   // size=0, offset=4 //  hashcode: 0x7DA6A91F (dec: 2108074271), parent name: 'GENERIC_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *downSignal; // size=0, offset=8 //  hashcode: 0x068C71A3 (dec: 109867427), parent name: 'GENERIC_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_92fake // hashcode: 0x2B28B946 (dec: 724089158)
{
	long currentnum; // size=0, offset=0 //  hashcode: 0xCB95DB4C (dec: -879371444), parent name: 'GENERIC_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long streamID;   // size=0, offset=4 //  hashcode: 0x842B8CE8 (dec: -2077520664), parent name: 'GENERIC_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char toname[16]; // size=16, offset=8 //  hashcode: 0x1D7B82C3 (dec: 494633667), parent name: 'GENERIC_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_93fake // hashcode: 0x3FEE65FD (dec: 1072588285)
{
	char num;			   // size=0, offset=0 //  hashcode: 0xF66FD11F (dec: -160444129), parent name: 'GENERIC_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char vel;			   // size=0, offset=1 //  hashcode: 0xD48C2A4F (dec: -729011633), parent name: 'GENERIC_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short misc;			   // size=0, offset=2 //  hashcode: 0x08770EAA (dec: 142020266), parent name: 'GENERIC_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char flags;			   // size=0, offset=4 //  hashcode: 0x26720826 (dec: 645007398), parent name: 'GENERIC_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char timeToLive;	   // size=0, offset=5 //  hashcode: 0x076A60D2 (dec: 124412114), parent name: 'GENERIC_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short dummy2;		   // size=0, offset=6 //  hashcode: 0x8456AC47 (dec: -2074694585), parent name: 'GENERIC_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Object *object; // size=0, offset=8 //  hashcode: 0x6BBC65A7 (dec: 1807508903), parent name: 'GENERIC_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_94fake // hashcode: 0x2187C418 (dec: 562545688)
{
	long index;  // size=0, offset=0 //  hashcode: 0xE53B57BB (dec: -449095749), parent name: 'GENERIC_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0xA1F84863 (dec: -1577564061), parent name: 'GENERIC_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_95fake // hashcode: 0xC3BE2612 (dec: -1010948590)
{
	short type; // size=0, offset=0 //  hashcode: 0x437FC46A (dec: 1132446826), parent name: 'GENERIC_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time; // size=0, offset=2 //  hashcode: 0x15E0B885 (dec: 367048837), parent name: 'GENERIC_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_96fake // hashcode: 0x6F9D8F2A (dec: 1872596778)
{
	long time;   // size=0, offset=0 //  hashcode: 0xAE8C175C (dec: -1366550692), parent name: 'GENERIC_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0xE341EC42 (dec: -482218942), parent name: 'GENERIC_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_97fake // hashcode: 0x8C5A8268 (dec: -1940225432)
{
	void *intro;			  // size=0, offset=0 //  hashcode: 0x029A6E04 (dec: 43675140), parent name: 'GENERIC_97fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0xE133502A (dec: -516730838), parent name: 'GENERIC_97fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_98fake // hashcode: 0x6FCBF109 (dec: 1875636489)
{
	char world[9]; // size=9, offset=0 //  hashcode: 0x46937D81 (dec: 1184071041), parent name: 'GENERIC_98fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char level[9]; // size=9, offset=9 //  hashcode: 0x69109A12 (dec: 1762695698), parent name: 'GENERIC_98fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_99fake // hashcode: 0x5FBCF732 (dec: 1606219570)
{
	struct Signal *signal; // size=0, offset=0 //  hashcode: 0x89FD252D (dec: -1979898579), parent name: 'GENERIC_99fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long times;			   // size=0, offset=4 //  hashcode: 0x76045DE9 (dec: 1979997673), parent name: 'GENERIC_99fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_100fake // hashcode: 0xFCBB75BF (dec: -54823489)
{
	unsigned char r;   // size=0, offset=0 //  hashcode: 0xA66A6B43 (dec: -1502975165), parent name: 'GENERIC_100fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char g;   // size=0, offset=1 //  hashcode: 0xAE8F868D (dec: -1366325619), parent name: 'GENERIC_100fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char b;   // size=0, offset=2 //  hashcode: 0x6AD3078C (dec: 1792214924), parent name: 'GENERIC_100fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad; // size=0, offset=3 //  hashcode: 0x927CDA47 (dec: -1837311417), parent name: 'GENERIC_100fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_101fake // hashcode: 0xBB191744 (dec: -1155983548)
{
	short x;	 // size=0, offset=0 //  hashcode: 0xEA9896DA (dec: -359098662), parent name: 'GENERIC_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;	 // size=0, offset=2 //  hashcode: 0x9B3C5706 (dec: -1690544378), parent name: 'GENERIC_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time;  // size=0, offset=4 //  hashcode: 0x3C6F0ED5 (dec: 1013911253), parent name: 'GENERIC_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short index; // size=0, offset=6 //  hashcode: 0x9646A554 (dec: -1773755052), parent name: 'GENERIC_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char *text;  // size=0, offset=8 //  hashcode: 0x0C176EFC (dec: 202862332), parent name: 'GENERIC_101fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union GENERIC_102fake // Hashcode: 0x8AEB4EF4 (dec: -1964290316)
{
	struct GENERIC_79fake misc[3];		// size=12, offset=0
	struct _CameraKey *cameraKey;		// size=24, offset=0
	struct GENERIC_80fake teleport;		// size=16, offset=0
	struct GENERIC_81fake cameraValue;  // size=8, offset=0
	struct GENERIC_82fake miscValue;	// size=8, offset=0
	struct GENERIC_83fake logicValue;   // size=8, offset=0
	long timer;							// size=0, offset=0
	long times;							// size=0, offset=0
	long lightGroup;					// size=0, offset=0
	long farPlane;						// size=0, offset=0
	long cameraAdjust;					// size=0, offset=0
	long cameraMode;					// size=0, offset=0
	long cameraLock;					// size=0, offset=0
	long cameraUnlock;					// size=0, offset=0
	long cameraSmooth;					// size=0, offset=0
	long cameraTimer;					// size=0, offset=0
	struct GENERIC_84fake cameraShake;  // size=8, offset=0
	long cameraSave;					// size=0, offset=0
	long cameraRestore;					// size=0, offset=0
	struct _BGObject *bgObject;			// size=24, offset=0
	long value[2];						// size=8, offset=0
	struct GENERIC_85fake sound;		// size=12, offset=0
	void *intro;						// size=0, offset=0
	long deathZ;						// size=0, offset=0
	struct GENERIC_86fake dsignal;		// size=8, offset=0
	void *mirror;						// size=0, offset=0
	long fogNear;						// size=0, offset=0
	long fogFar;						// size=0, offset=0
	struct GENERIC_87fake gotoFrame;	// size=8, offset=0
	struct GENERIC_88fake changeModel;  // size=8, offset=0
	void *vmObject;						// size=0, offset=0
	struct GENERIC_89fake logic;		// size=8, offset=0
	void *callSignal;					// size=0, offset=0
	struct _SVector offset;				// size=8, offset=0
	struct Signal *gotoLabel;			// size=0, offset=0
	struct Signal *gosubLabel;			// size=0, offset=0
	struct GENERIC_90fake control;		// size=8, offset=0
	struct GENERIC_91fake zSignal;		// size=12, offset=0
	struct GENERIC_92fake StreamLevel;  // size=24, offset=0
	struct GENERIC_93fake shards;		// size=12, offset=0
	struct GENERIC_94fake cameraSpline; // size=8, offset=0
	struct GENERIC_95fake screenWipe;   // size=4, offset=0
	long voiceSitId;					// size=0, offset=0
	struct GENERIC_96fake introFX;		// size=8, offset=0
	struct GENERIC_97fake introActive;  // size=8, offset=0
	struct GENERIC_98fake levelChange;  // size=18, offset=0
	long blendStart;					// size=0, offset=0
	struct GENERIC_99fake setTimes;		// size=8, offset=0
	struct GENERIC_100fake color;		// size=4, offset=0
	struct GENERIC_101fake print;		// size=12, offset=0
	long slideAngle;					// size=0, offset=0
};

union GENERIC_103fake // Hashcode: 0x026DBB18 (dec: 40745752)
{
	struct _HSphere *hsphere; // size=20, offset=0
	struct _HBox *hbox;		  // size=28, offset=0
	struct _HFace *hface;	 // size=12, offset=0
};

union GENERIC_108fake // Hashcode: 0x9DEF46FE (dec: -1645263106)
{
	struct _VMOffset moveOffsets;		// size=6, offset=0
	struct _VMColorOffset colorOffsets; // size=3, offset=0
};

struct GENERIC_110fake // hashcode: 0x47BB27E3 (dec: 1203447779)
{
	struct MultiSpline *posSpline;	// size=0, offset=0 //  hashcode: 0x73D90213 (dec: 1943601683), parent name: 'GENERIC_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSpline *targetSpline; // size=0, offset=4 //  hashcode: 0x8ECDD210 (dec: -1899113968), parent name: 'GENERIC_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector lastSplinePos;	// size=8, offset=8 //  hashcode: 0x266D71FA (dec: 644706810), parent name: 'GENERIC_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short splinePointAhead;			  // size=0, offset=16 //  hashcode: 0x4DF390C6 (dec: 1307807942), parent name: 'GENERIC_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short cinema_done;				  // size=0, offset=18 //  hashcode: 0xB6D03DB0 (dec: -1227866704), parent name: 'GENERIC_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	int splinecam_currkey;			  // size=0, offset=20 //  hashcode: 0xB4A4322D (dec: -1264307667), parent name: 'GENERIC_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	int splinecam_helpkey;			  // size=0, offset=24 //  hashcode: 0xB6CC06C3 (dec: -1228142909), parent name: 'GENERIC_110fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_111fake // hashcode: 0x7653AB12 (dec: 1985194770)
{
	struct _Position offset;   // size=6, offset=0 //  hashcode: 0x1E5B5D9C (dec: 509304220), parent name: 'GENERIC_111fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _Rotation rotation; // size=8, offset=6 //  hashcode: 0x3D21DE08 (dec: 1025629704), parent name: 'GENERIC_111fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long focusDistance;		   // size=0, offset=16 //  hashcode: 0x7B401256 (dec: 2067796566), parent name: 'GENERIC_111fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_112fake // hashcode: 0x14A3DFB3 (dec: 346283955)
{
	struct _TFace *tface;				 // size=12, offset=0 //  hashcode: 0xC9D3B281 (dec: -908873087), parent name: 'GENERIC_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *oldTFace;			 // size=12, offset=4 //  hashcode: 0x75981F0D (dec: 1972903693), parent name: 'GENERIC_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector oldTargetRot;		 // size=8, offset=8 //  hashcode: 0x5B789598 (dec: 1534629272), parent name: 'GENERIC_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long timer;							 // size=0, offset=16 //  hashcode: 0xFF69DE91 (dec: -9838959), parent name: 'GENERIC_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector oldFocusInstancePos; // size=8, offset=20 //  hashcode: 0x2579345C (dec: 628700252), parent name: 'GENERIC_112fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_113fake // hashcode: 0xC20360C6 (dec: -1039966010)
{
	long stopTimer;			 // size=0, offset=0 //  hashcode: 0x5861D8C4 (dec: 1482807492), parent name: 'GENERIC_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long stopHit;			 // size=0, offset=4 //  hashcode: 0x9541B906 (dec: -1790854906), parent name: 'GENERIC_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *tface;	// size=12, offset=8 //  hashcode: 0x27908423 (dec: 663782435), parent name: 'GENERIC_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *oldTFace; // size=12, offset=12 //  hashcode: 0xFE478BC5 (dec: -28865595), parent name: 'GENERIC_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long hit;				 // size=0, offset=16 //  hashcode: 0x5FF8A248 (dec: 1610129992), parent name: 'GENERIC_113fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_114fake // hashcode: 0xDFE61644 (dec: -538569148)
{
	struct GENERIC_110fake Cinematic; // size=28, offset=0 //  hashcode: 0x0C7B35C4 (dec: 209401284), parent name: 'GENERIC_114fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct GENERIC_111fake Idle;	  // size=20, offset=28 //  hashcode: 0x7FEBDAAF (dec: 2146163375), parent name: 'GENERIC_114fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct GENERIC_112fake Behind;	// size=28, offset=48 //  hashcode: 0xB8E2421E (dec: -1193131490), parent name: 'GENERIC_114fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct GENERIC_113fake Follow;	// size=20, offset=76 //  hashcode: 0x18DEBDF5 (dec: 417250805), parent name: 'GENERIC_114fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct evAnimationInstanceSwitchData // hashcode: 0xEE7F2A6C (dec: -293655956)
{
	struct _Instance *instance; // size=616, offset=0 //  hashcode: 0xAD384A7D (dec: -1388819843), parent name: 'evAnimationInstanceSwitchData', parent hashcode: 0xFFFFFFFF (dec: -1)
	int anim;					// size=0, offset=4 //  hashcode: 0xF1A7C150 (dec: -240664240), parent name: 'evAnimationInstanceSwitchData', parent hashcode: 0xFFFFFFFF (dec: -1)
	int frame;					// size=0, offset=8 //  hashcode: 0xE33F1D82 (dec: -482402942), parent name: 'evAnimationInstanceSwitchData', parent hashcode: 0xFFFFFFFF (dec: -1)
	int frames;					// size=0, offset=12 //  hashcode: 0x2A2EEDC3 (dec: 707718595), parent name: 'evAnimationInstanceSwitchData', parent hashcode: 0xFFFFFFFF (dec: -1)
	int mode;					// size=0, offset=16 //  hashcode: 0xEC030B8D (dec: -335344755), parent name: 'evAnimationInstanceSwitchData', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union GENERIC_201fake // Hashcode: 0x7031E694 (dec: 1882318484)
{
	struct _Instance *target;	 // size=616, offset=0
	struct _Position position;	// size=6, offset=0
	struct _Rotation direction;   // size=8, offset=0
	struct _Position throwVector; // size=6, offset=0
};

struct evControlSaveDataData // hashcode: 0xA76A68A9 (dec: -1486198615)
{
	long length; // size=0, offset=0 //  hashcode: 0x34FAFAA2 (dec: 888863394), parent name: 'evControlSaveDataData', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *data;  // size=0, offset=4 //  hashcode: 0x33E74DD5 (dec: 870796757), parent name: 'evControlSaveDataData', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GenericTune // hashcode: 0x1B714C34 (dec: 460409908)
{
	long flags;		   // size=0, offset=0 //  hashcode: 0x9FE49857 (dec: -1612408745), parent name: 'GenericTune', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *shatterData; // size=0, offset=4 //  hashcode: 0xAB87B3A7 (dec: -1417170009), parent name: 'GenericTune', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_222fake // hashcode: 0x845FCA71 (dec: -2074097039)
{
	struct _Instance *parent; // size=616, offset=0 //  hashcode: 0xD2200C92 (dec: -769651566), parent name: 'GENERIC_222fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long segment;			  // size=0, offset=4 //  hashcode: 0x19F359CC (dec: 435378636), parent name: 'GENERIC_222fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct GENERIC_223fake // hashcode: 0x3B97D7B3 (dec: 999806899)
{
	short xVel;  // size=0, offset=0 //  hashcode: 0x1592951E (dec: 361927966), parent name: 'GENERIC_223fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short yVel;  // size=0, offset=2 //  hashcode: 0xA005DC83 (dec: -1610228605), parent name: 'GENERIC_223fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zVel;  // size=0, offset=4 //  hashcode: 0x7C084D84 (dec: 2080918916), parent name: 'GENERIC_223fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short xAccl; // size=0, offset=6 //  hashcode: 0x562D45E5 (dec: 1445807589), parent name: 'GENERIC_223fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short yAccl; // size=0, offset=8 //  hashcode: 0x32213111 (dec: 841036049), parent name: 'GENERIC_223fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zAccl; // size=0, offset=10 //  hashcode: 0xD8C308D7 (dec: -658306857), parent name: 'GENERIC_223fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union GENERIC_224fake // Hashcode: 0xD13E5F44 (dec: -784441532)
{
	struct GENERIC_222fake flame; // size=8, offset=0
	struct GENERIC_223fake phys;  // size=12, offset=0
};

typedef struct evAnimationInstanceSwitchData evAnimationInstanceSwitchData;

typedef struct evControlSaveDataData evControlSaveDataData;

typedef struct GenericTune GenericTune;

extern void GenericInit(struct _Instance *instance, struct GameTracker *gameTracker); // 0x8003E194

extern void GenericCollide(struct _Instance *instance, struct GameTracker *gameTracker); // 0x8003E2D0

extern void GenericProcess(struct _Instance *instance, struct GameTracker *gameTracker); // 0x8003E2D8

extern unsigned long GenericQuery(struct _Instance *instance, unsigned long query); // 0x8003E32C

extern void GenericMessage(struct _Instance *instance, unsigned long message, unsigned long data); // 0x8003E4A4

extern void GenericRelocateTune(struct Object *object, long offset); // 0x8003E620

#endif
