#ifndef MAING2_H
#define MAING2_H

struct MAING2_68fake // hashcode: 0x185E0D79 (dec: 408817017)
{
	unsigned long (*function)(); // size=0, offset=0 //  hashcode: 0xE3D729C8 (dec: -472438328), parent name: 'MAING2_68fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *fnData;				 // size=0, offset=4 //  hashcode: 0x36BE99EA (dec: 918460906), parent name: 'MAING2_68fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_69fake // hashcode: 0xCA6F72D0 (dec: -898665776)
{
	struct _G2SVector3_Type base;   // size=6, offset=0 //  hashcode: 0xAF57D453 (dec: -1353198509), parent name: 'MAING2_69fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2SVector3_Type offset; // size=6, offset=6 //  hashcode: 0x681FC32F (dec: 1746912047), parent name: 'MAING2_69fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_70fake // hashcode: 0xA5212C4F (dec: -1524552625)
{
	struct _G2Quat_Type src;  // size=8, offset=0 //  hashcode: 0xDBE2B604 (dec: -605899260), parent name: 'MAING2_70fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2Quat_Type dest; // size=8, offset=8 //  hashcode: 0x6564FD96 (dec: 1701117334), parent name: 'MAING2_70fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union MAING2_71fake // Hashcode: 0xC6D143DA (dec: -959364134)
{
	struct MAING2_68fake callback; // size=8, offset=0
	struct MAING2_69fake vector;   // size=12, offset=0
	struct MAING2_70fake quat;	 // size=16, offset=0
};

union MAING2_72fake // Hashcode: 0x5E3F6632 (dec: 1581213234)
{
	long color;				// size=0, offset=0
	struct _RGBAColor rgba; // size=4, offset=0
};

union MAING2_73fake // Hashcode: 0x70E51DC1 (dec: 1894063553)
{
	long l;		// size=0, offset=0
	short s[2]; // size=4, offset=0
	char c[4];  // size=4, offset=0
};

struct MAING2_74fake // hashcode: 0x00BB36C8 (dec: 12269256)
{
	union MAING2_73fake size; // size=4, offset=0 //  hashcode: 0xE13C9FA8 (dec: -516120664), parent name: 'MAING2_74fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_75fake // hashcode: 0x7DFBBE63 (dec: 2113650275)
{
	short x;				// size=0, offset=0 //  hashcode: 0xF0CBB7A7 (dec: -255084633), parent name: 'MAING2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;				// size=0, offset=2 //  hashcode: 0x0035EC19 (dec: 3533849), parent name: 'MAING2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;				// size=0, offset=4 //  hashcode: 0x0AE050D0 (dec: 182472912), parent name: 'MAING2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zrot;				// size=0, offset=6 //  hashcode: 0x22456D14 (dec: 574975252), parent name: 'MAING2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector offset; // size=8, offset=8 //  hashcode: 0x8A9F8932 (dec: -1969256142), parent name: 'MAING2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_76fake // hashcode: 0xF93E7BDB (dec: -113345573)
{
	long index; // size=0, offset=0 //  hashcode: 0x778F3901 (dec: 2005874945), parent name: 'MAING2_76fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0xB661DA85 (dec: -1235101051), parent name: 'MAING2_76fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_77fake // hashcode: 0x1E8B6A34 (dec: 512453172)
{
	long index; // size=0, offset=0 //  hashcode: 0x6104FD5B (dec: 1627716955), parent name: 'MAING2_77fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0xC1B4CB2A (dec: -1045116118), parent name: 'MAING2_77fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_78fake // hashcode: 0xC7499D23 (dec: -951476957)
{
	long index; // size=0, offset=0 //  hashcode: 0xB328A419 (dec: -1289182183), parent name: 'MAING2_78fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0x4A17B654 (dec: 1243067988), parent name: 'MAING2_78fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_79fake // hashcode: 0x5A234D6D (dec: 1512263021)
{
	long time;  // size=0, offset=0 //  hashcode: 0x41D393C9 (dec: 1104384969), parent name: 'MAING2_79fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long scale; // size=0, offset=4 //  hashcode: 0x0991229D (dec: 160506525), parent name: 'MAING2_79fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_80fake // hashcode: 0x3BBDE4B1 (dec: 1002300593)
{
	long action;   // size=0, offset=0 //  hashcode: 0xBE73B2FB (dec: -1099713797), parent name: 'MAING2_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value[2]; // size=8, offset=4 //  hashcode: 0xFDE8AB86 (dec: -35083386), parent name: 'MAING2_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_81fake // hashcode: 0x315FC480 (dec: 828359808)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x49F6DA1A (dec: 1240914458), parent name: 'MAING2_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *data;  // size=0, offset=4 //  hashcode: 0x025DD337 (dec: 39703351), parent name: 'MAING2_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_82fake // hashcode: 0x07EF27C6 (dec: 133113798)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x71BC4F1C (dec: 1908166428), parent name: 'MAING2_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long frame;  // size=0, offset=4 //  hashcode: 0x98674963 (dec: -1738061469), parent name: 'MAING2_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_83fake // hashcode: 0x6AE7296F (dec: 1793534319)
{
	void *intro; // size=0, offset=0 //  hashcode: 0xE7B43B33 (dec: -407618765), parent name: 'MAING2_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long model;  // size=0, offset=4 //  hashcode: 0x348D5429 (dec: 881677353), parent name: 'MAING2_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_84fake // hashcode: 0x963FA368 (dec: -1774214296)
{
	unsigned char target;	 // size=0, offset=0 //  hashcode: 0xF4441E9B (dec: -196862309), parent name: 'MAING2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source1;	// size=0, offset=1 //  hashcode: 0xC632FE8F (dec: -969736561), parent name: 'MAING2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source2;	// size=0, offset=2 //  hashcode: 0x0A142D99 (dec: 169094553), parent name: 'MAING2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad;		  // size=0, offset=3 //  hashcode: 0xEF57436B (dec: -279493781), parent name: 'MAING2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0x943BBF8F (dec: -1808023665), parent name: 'MAING2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_85fake // hashcode: 0xADA56E41 (dec: -1381667263)
{
	long timer;  // size=0, offset=0 //  hashcode: 0x1C13AE8F (dec: 471051919), parent name: 'MAING2_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long action; // size=0, offset=4 //  hashcode: 0x39B20ABD (dec: 967969469), parent name: 'MAING2_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_86fake // hashcode: 0x270BADD7 (dec: 655076823)
{
	short index;					// size=0, offset=0 //  hashcode: 0x575D00FB (dec: 1465712891), parent name: 'MAING2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;						// size=0, offset=2 //  hashcode: 0x30AED12F (dec: 816763183), parent name: 'MAING2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *upSignal;   // size=0, offset=4 //  hashcode: 0xB8270FD0 (dec: -1205399600), parent name: 'MAING2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *downSignal; // size=0, offset=8 //  hashcode: 0x1B7ED911 (dec: 461297937), parent name: 'MAING2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_87fake // hashcode: 0xEB3FCB13 (dec: -348140781)
{
	long currentnum; // size=0, offset=0 //  hashcode: 0x6C3B222A (dec: 1815814698), parent name: 'MAING2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long streamID;   // size=0, offset=4 //  hashcode: 0x97E3762D (dec: -1746700755), parent name: 'MAING2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char toname[16]; // size=16, offset=8 //  hashcode: 0x328E59D4 (dec: 848189908), parent name: 'MAING2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_88fake // hashcode: 0x60CF7D1D (dec: 1624210717)
{
	char num;			   // size=0, offset=0 //  hashcode: 0x8D7CF675 (dec: -1921190283), parent name: 'MAING2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char vel;			   // size=0, offset=1 //  hashcode: 0xEB4FB568 (dec: -347097752), parent name: 'MAING2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short misc;			   // size=0, offset=2 //  hashcode: 0x7A2C3ADE (dec: 2049719006), parent name: 'MAING2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char flags;			   // size=0, offset=4 //  hashcode: 0x8DAC0A9F (dec: -1918104929), parent name: 'MAING2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char timeToLive;	   // size=0, offset=5 //  hashcode: 0x732CC3BC (dec: 1932313532), parent name: 'MAING2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short dummy2;		   // size=0, offset=6 //  hashcode: 0x30F35645 (dec: 821253701), parent name: 'MAING2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Object *object; // size=0, offset=8 //  hashcode: 0x828D58D3 (dec: -2104665901), parent name: 'MAING2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_89fake // hashcode: 0x56C22FD8 (dec: 1455566808)
{
	long index;  // size=0, offset=0 //  hashcode: 0x40356DE2 (dec: 1077243362), parent name: 'MAING2_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0x34F5FC0C (dec: 888536076), parent name: 'MAING2_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_90fake // hashcode: 0x592574ED (dec: 1495626989)
{
	short type; // size=0, offset=0 //  hashcode: 0xD84FBDDE (dec: -665862690), parent name: 'MAING2_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time; // size=0, offset=2 //  hashcode: 0xB0788858 (dec: -1334278056), parent name: 'MAING2_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_91fake // hashcode: 0x9687CDB7 (dec: -1769484873)
{
	long time;   // size=0, offset=0 //  hashcode: 0xAC33FBD6 (dec: -1405879338), parent name: 'MAING2_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0xD2EF67B4 (dec: -756062284), parent name: 'MAING2_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_92fake // hashcode: 0x030F75EC (dec: 51344876)
{
	void *intro;			  // size=0, offset=0 //  hashcode: 0xC498CFA3 (dec: -996618333), parent name: 'MAING2_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0x75F74A82 (dec: 1979140738), parent name: 'MAING2_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_93fake // hashcode: 0x0B31CF5B (dec: 187813723)
{
	char world[9]; // size=9, offset=0 //  hashcode: 0xE05821DA (dec: -531095078), parent name: 'MAING2_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char level[9]; // size=9, offset=9 //  hashcode: 0x6488BB70 (dec: 1686682480), parent name: 'MAING2_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_94fake // hashcode: 0xF1091DD7 (dec: -251060777)
{
	struct Signal *signal; // size=0, offset=0 //  hashcode: 0xED42104B (dec: -314437557), parent name: 'MAING2_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long times;			   // size=0, offset=4 //  hashcode: 0x37B1EC03 (dec: 934407171), parent name: 'MAING2_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_95fake // hashcode: 0x150B383A (dec: 353056826)
{
	unsigned char r;   // size=0, offset=0 //  hashcode: 0x518EDE56 (dec: 1368317526), parent name: 'MAING2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char g;   // size=0, offset=1 //  hashcode: 0x619F8FD8 (dec: 1637847000), parent name: 'MAING2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char b;   // size=0, offset=2 //  hashcode: 0x27E3A90A (dec: 669231370), parent name: 'MAING2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad; // size=0, offset=3 //  hashcode: 0x379F2E6D (dec: 933178989), parent name: 'MAING2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct MAING2_96fake // hashcode: 0x6D1A3377 (dec: 1830433655)
{
	short x;	 // size=0, offset=0 //  hashcode: 0x97C5C876 (dec: -1748645770), parent name: 'MAING2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;	 // size=0, offset=2 //  hashcode: 0x80501E68 (dec: -2142232984), parent name: 'MAING2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time;  // size=0, offset=4 //  hashcode: 0x4E150787 (dec: 1310001031), parent name: 'MAING2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short index; // size=0, offset=6 //  hashcode: 0xDF310556 (dec: -550435498), parent name: 'MAING2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char *text;  // size=0, offset=8 //  hashcode: 0x88DAEBFD (dec: -1998918659), parent name: 'MAING2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union MAING2_97fake // Hashcode: 0x7DA29EA1 (dec: 2107809441)
{
	struct MAING2_74fake misc[3];	  // size=12, offset=0
	struct _CameraKey *cameraKey;	  // size=24, offset=0
	struct MAING2_75fake teleport;	 // size=16, offset=0
	struct MAING2_76fake cameraValue;  // size=8, offset=0
	struct MAING2_77fake miscValue;	// size=8, offset=0
	struct MAING2_78fake logicValue;   // size=8, offset=0
	long timer;						   // size=0, offset=0
	long times;						   // size=0, offset=0
	long lightGroup;				   // size=0, offset=0
	long farPlane;					   // size=0, offset=0
	long cameraAdjust;				   // size=0, offset=0
	long cameraMode;				   // size=0, offset=0
	long cameraLock;				   // size=0, offset=0
	long cameraUnlock;				   // size=0, offset=0
	long cameraSmooth;				   // size=0, offset=0
	long cameraTimer;				   // size=0, offset=0
	struct MAING2_79fake cameraShake;  // size=8, offset=0
	long cameraSave;				   // size=0, offset=0
	long cameraRestore;				   // size=0, offset=0
	struct _BGObject *bgObject;		   // size=24, offset=0
	long value[2];					   // size=8, offset=0
	struct MAING2_80fake sound;		   // size=12, offset=0
	void *intro;					   // size=0, offset=0
	long deathZ;					   // size=0, offset=0
	struct MAING2_81fake dsignal;	  // size=8, offset=0
	void *mirror;					   // size=0, offset=0
	long fogNear;					   // size=0, offset=0
	long fogFar;					   // size=0, offset=0
	struct MAING2_82fake gotoFrame;	// size=8, offset=0
	struct MAING2_83fake changeModel;  // size=8, offset=0
	void *vmObject;					   // size=0, offset=0
	struct MAING2_84fake logic;		   // size=8, offset=0
	void *callSignal;				   // size=0, offset=0
	struct _SVector offset;			   // size=8, offset=0
	struct Signal *gotoLabel;		   // size=0, offset=0
	struct Signal *gosubLabel;		   // size=0, offset=0
	struct MAING2_85fake control;	  // size=8, offset=0
	struct MAING2_86fake zSignal;	  // size=12, offset=0
	struct MAING2_87fake StreamLevel;  // size=24, offset=0
	struct MAING2_88fake shards;	   // size=12, offset=0
	struct MAING2_89fake cameraSpline; // size=8, offset=0
	struct MAING2_90fake screenWipe;   // size=4, offset=0
	long voiceSitId;				   // size=0, offset=0
	struct MAING2_91fake introFX;	  // size=8, offset=0
	struct MAING2_92fake introActive;  // size=8, offset=0
	struct MAING2_93fake levelChange;  // size=18, offset=0
	long blendStart;				   // size=0, offset=0
	struct MAING2_94fake setTimes;	 // size=8, offset=0
	struct MAING2_95fake color;		   // size=4, offset=0
	struct MAING2_96fake print;		   // size=12, offset=0
	long slideAngle;				   // size=0, offset=0
};

union MAING2_98fake // Hashcode: 0x653CE1ED (dec: 1698488813)
{
	struct _HSphere *hsphere; // size=20, offset=0
	struct _HBox *hbox;		  // size=28, offset=0
	struct _HFace *hface;	 // size=12, offset=0
};

union MAING2_103fake // Hashcode: 0xCF4FF1EC (dec: -816844308)
{
	struct _VMOffset moveOffsets;		// size=6, offset=0
	struct _VMColorOffset colorOffsets; // size=3, offset=0
};

extern enum _G2Bool_Enum MainG2_InitEngine(void *appData, unsigned int screenWidth, unsigned int screenHeight, char *filesystemName); // 0x80095D8C

extern void MainG2_ShutDownEngine(void *appData); // 0x80095D94

#endif
