#ifndef QUATG2_H
#define QUATG2_H

struct QUATG2_68fake // hashcode: 0xA1C67BF2 (dec: -1580827662)
{
	unsigned long (*function)(); // size=0, offset=0 //  hashcode: 0x7E0EC4B0 (dec: 2114897072), parent name: 'QUATG2_68fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *fnData;				 // size=0, offset=4 //  hashcode: 0x37AE4A24 (dec: 934169124), parent name: 'QUATG2_68fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_69fake // hashcode: 0x114A7B8B (dec: 290093963)
{
	struct _G2SVector3_Type base;   // size=6, offset=0 //  hashcode: 0x55C9CAA6 (dec: 1439287974), parent name: 'QUATG2_69fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2SVector3_Type offset; // size=6, offset=6 //  hashcode: 0xE52AB5E2 (dec: -450185758), parent name: 'QUATG2_69fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_70fake // hashcode: 0xB1558495 (dec: -1319795563)
{
	struct _G2Quat_Type src;  // size=8, offset=0 //  hashcode: 0x49394C82 (dec: 1228491906), parent name: 'QUATG2_70fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2Quat_Type dest; // size=8, offset=8 //  hashcode: 0x27F11A3C (dec: 670112316), parent name: 'QUATG2_70fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union QUATG2_71fake // Hashcode: 0x6D09A304 (dec: 1829348100)
{
	struct QUATG2_68fake callback; // size=8, offset=0
	struct QUATG2_69fake vector;   // size=12, offset=0
	struct QUATG2_70fake quat;	 // size=16, offset=0
};

union QUATG2_72fake // Hashcode: 0xEADF8295 (dec: -354450795)
{
	long color;				// size=0, offset=0
	struct _RGBAColor rgba; // size=4, offset=0
};

union QUATG2_73fake // Hashcode: 0x54B829DE (dec: 1421355486)
{
	long l;		// size=0, offset=0
	short s[2]; // size=4, offset=0
	char c[4];  // size=4, offset=0
};

struct QUATG2_74fake // hashcode: 0x8B57B109 (dec: -1957187319)
{
	union QUATG2_73fake size; // size=4, offset=0 //  hashcode: 0x8D9D7485 (dec: -1919060859), parent name: 'QUATG2_74fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_75fake // hashcode: 0xB3397F1F (dec: -1288077537)
{
	short x;				// size=0, offset=0 //  hashcode: 0xC0DC0626 (dec: -1059322330), parent name: 'QUATG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;				// size=0, offset=2 //  hashcode: 0x74ED953C (dec: 1961727292), parent name: 'QUATG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;				// size=0, offset=4 //  hashcode: 0xB0B5CA69 (dec: -1330263447), parent name: 'QUATG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zrot;				// size=0, offset=6 //  hashcode: 0x96A046A9 (dec: -1767881047), parent name: 'QUATG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector offset; // size=8, offset=8 //  hashcode: 0x737459DD (dec: 1937005021), parent name: 'QUATG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_76fake // hashcode: 0xFBCD4E4D (dec: -70431155)
{
	long index; // size=0, offset=0 //  hashcode: 0xC3EADC5A (dec: -1008018342), parent name: 'QUATG2_76fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0xE9B02EB4 (dec: -374329676), parent name: 'QUATG2_76fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_77fake // hashcode: 0xAF439674 (dec: -1354525068)
{
	long index; // size=0, offset=0 //  hashcode: 0xF960286C (dec: -111138708), parent name: 'QUATG2_77fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0xE58018CC (dec: -444589876), parent name: 'QUATG2_77fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_78fake // hashcode: 0x0C461A01 (dec: 205920769)
{
	long index; // size=0, offset=0 //  hashcode: 0xBC4FAC33 (dec: -1135629261), parent name: 'QUATG2_78fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0x46AE9B26 (dec: 1185848102), parent name: 'QUATG2_78fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_79fake // hashcode: 0x81AD25C4 (dec: -2119359036)
{
	long time;  // size=0, offset=0 //  hashcode: 0x3CB0E2FD (dec: 1018225405), parent name: 'QUATG2_79fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long scale; // size=0, offset=4 //  hashcode: 0x84171D4C (dec: -2078859956), parent name: 'QUATG2_79fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_80fake // hashcode: 0x16A536FC (dec: 379926268)
{
	long action;   // size=0, offset=0 //  hashcode: 0xE4F218D6 (dec: -453895978), parent name: 'QUATG2_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value[2]; // size=8, offset=4 //  hashcode: 0x9433CA49 (dec: -1808545207), parent name: 'QUATG2_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_81fake // hashcode: 0x8AA2BCBA (dec: -1969046342)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x86F7A9E7 (dec: -2030589465), parent name: 'QUATG2_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *data;  // size=0, offset=4 //  hashcode: 0x445B2F84 (dec: 1146826628), parent name: 'QUATG2_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_82fake // hashcode: 0xF2E48EAD (dec: -219902291)
{
	void *intro; // size=0, offset=0 //  hashcode: 0xA89F27BA (dec: -1465964614), parent name: 'QUATG2_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long frame;  // size=0, offset=4 //  hashcode: 0x6996EF75 (dec: 1771499381), parent name: 'QUATG2_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_83fake // hashcode: 0x88E8DE59 (dec: -1998004647)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x2DC3E29E (dec: 767812254), parent name: 'QUATG2_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long model;  // size=0, offset=4 //  hashcode: 0xAB636A01 (dec: -1419548159), parent name: 'QUATG2_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_84fake // hashcode: 0x3E139F3B (dec: 1041473339)
{
	unsigned char target;	 // size=0, offset=0 //  hashcode: 0x784E6E2C (dec: 2018405932), parent name: 'QUATG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source1;	// size=0, offset=1 //  hashcode: 0x5B272DB6 (dec: 1529294262), parent name: 'QUATG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source2;	// size=0, offset=2 //  hashcode: 0xB3147B03 (dec: -1290503421), parent name: 'QUATG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad;		  // size=0, offset=3 //  hashcode: 0x3E0C8642 (dec: 1041008194), parent name: 'QUATG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0xC45A2027 (dec: -1000726489), parent name: 'QUATG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_85fake // hashcode: 0xC113F901 (dec: -1055655679)
{
	long timer;  // size=0, offset=0 //  hashcode: 0x28D98911 (dec: 685345041), parent name: 'QUATG2_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long action; // size=0, offset=4 //  hashcode: 0xED7A4B2A (dec: -310752470), parent name: 'QUATG2_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_86fake // hashcode: 0x4FC3FFDF (dec: 1338245087)
{
	short index;					// size=0, offset=0 //  hashcode: 0xA5BE9E8C (dec: -1514234228), parent name: 'QUATG2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;						// size=0, offset=2 //  hashcode: 0x31C95B4D (dec: 835279693), parent name: 'QUATG2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *upSignal;   // size=0, offset=4 //  hashcode: 0xF7698EBA (dec: -144077126), parent name: 'QUATG2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *downSignal; // size=0, offset=8 //  hashcode: 0x08416BCE (dec: 138505166), parent name: 'QUATG2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_87fake // hashcode: 0xA833C256 (dec: -1473002922)
{
	long currentnum; // size=0, offset=0 //  hashcode: 0x76A6FF0D (dec: 1990655757), parent name: 'QUATG2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long streamID;   // size=0, offset=4 //  hashcode: 0x505D10EA (dec: 1348276458), parent name: 'QUATG2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char toname[16]; // size=16, offset=8 //  hashcode: 0xD99FEBA7 (dec: -643830873), parent name: 'QUATG2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_88fake // hashcode: 0x6FEDED81 (dec: 1877863809)
{
	char num;			   // size=0, offset=0 //  hashcode: 0xB8DF4F36 (dec: -1193324746), parent name: 'QUATG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char vel;			   // size=0, offset=1 //  hashcode: 0xFEB1124D (dec: -21949875), parent name: 'QUATG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short misc;			   // size=0, offset=2 //  hashcode: 0x260E1443 (dec: 638456899), parent name: 'QUATG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char flags;			   // size=0, offset=4 //  hashcode: 0x8F305278 (dec: -1892658568), parent name: 'QUATG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char timeToLive;	   // size=0, offset=5 //  hashcode: 0x99FCFF61 (dec: -1711472799), parent name: 'QUATG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short dummy2;		   // size=0, offset=6 //  hashcode: 0xD1B2A4C3 (dec: -776821565), parent name: 'QUATG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Object *object; // size=0, offset=8 //  hashcode: 0xB4CFA4ED (dec: -1261460243), parent name: 'QUATG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_89fake // hashcode: 0x052D36BF (dec: 86849215)
{
	long index;  // size=0, offset=0 //  hashcode: 0xC2FAADDC (dec: -1023758884), parent name: 'QUATG2_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0x44F71438 (dec: 1157043256), parent name: 'QUATG2_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_90fake // hashcode: 0x0D65CE5D (dec: 224775773)
{
	short type; // size=0, offset=0 //  hashcode: 0x86B6753D (dec: -2034862787), parent name: 'QUATG2_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time; // size=0, offset=2 //  hashcode: 0x9457EC3B (dec: -1806177221), parent name: 'QUATG2_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_91fake // hashcode: 0x6AE21199 (dec: 1793200537)
{
	long time;   // size=0, offset=0 //  hashcode: 0xFB72424F (dec: -76398001), parent name: 'QUATG2_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0xF2671D13 (dec: -228123373), parent name: 'QUATG2_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_92fake // hashcode: 0x083AB100 (dec: 138064128)
{
	void *intro;			  // size=0, offset=0 //  hashcode: 0xBFA3D682 (dec: -1079781758), parent name: 'QUATG2_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0x008CA9CC (dec: 9218508), parent name: 'QUATG2_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_93fake // hashcode: 0x8FB87BC9 (dec: -1883735095)
{
	char world[9]; // size=9, offset=0 //  hashcode: 0xF28EF52C (dec: -225512148), parent name: 'QUATG2_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char level[9]; // size=9, offset=9 //  hashcode: 0x7FD8C6EB (dec: 2144913131), parent name: 'QUATG2_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_94fake // hashcode: 0x030C756C (dec: 51148140)
{
	struct Signal *signal; // size=0, offset=0 //  hashcode: 0xAAE68223 (dec: -1427733981), parent name: 'QUATG2_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long times;			   // size=0, offset=4 //  hashcode: 0x9C5C1A92 (dec: -1671685486), parent name: 'QUATG2_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_95fake // hashcode: 0x767011EC (dec: 1987056108)
{
	unsigned char r;   // size=0, offset=0 //  hashcode: 0x9B574ACD (dec: -1688778035), parent name: 'QUATG2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char g;   // size=0, offset=1 //  hashcode: 0xFE688892 (dec: -26703726), parent name: 'QUATG2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char b;   // size=0, offset=2 //  hashcode: 0x2BD63F2D (dec: 735461165), parent name: 'QUATG2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad; // size=0, offset=3 //  hashcode: 0xFE34EEB5 (dec: -30085451), parent name: 'QUATG2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct QUATG2_96fake // hashcode: 0x6B18D9E4 (dec: 1796790756)
{
	short x;	 // size=0, offset=0 //  hashcode: 0x9C678974 (dec: -1670936204), parent name: 'QUATG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;	 // size=0, offset=2 //  hashcode: 0x90ED9719 (dec: -1863477479), parent name: 'QUATG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time;  // size=0, offset=4 //  hashcode: 0x13D095CE (dec: 332436942), parent name: 'QUATG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short index; // size=0, offset=6 //  hashcode: 0x831FDE64 (dec: -2095063452), parent name: 'QUATG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char *text;  // size=0, offset=8 //  hashcode: 0x02173CBB (dec: 35077307), parent name: 'QUATG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union QUATG2_97fake // Hashcode: 0xA9E9E3F2 (dec: -1444289550)
{
	struct QUATG2_74fake misc[3];	  // size=12, offset=0
	struct _CameraKey *cameraKey;	  // size=24, offset=0
	struct QUATG2_75fake teleport;	 // size=16, offset=0
	struct QUATG2_76fake cameraValue;  // size=8, offset=0
	struct QUATG2_77fake miscValue;	// size=8, offset=0
	struct QUATG2_78fake logicValue;   // size=8, offset=0
	long timer;						   // size=0, offset=0
	long times;						   // size=0, offset=0
	long lightGroup;				   // size=0, offset=0
	long farPlane;					   // size=0, offset=0
	long cameraAdjust;				   // size=0, offset=0
	long cameraMode;				   // size=0, offset=0
	long cameraLock;				   // size=0, offset=0
	long cameraUnlock;				   // size=0, offset=0
	long cameraSmooth;				   // size=0, offset=0
	long cameraTimer;				   // size=0, offset=0
	struct QUATG2_79fake cameraShake;  // size=8, offset=0
	long cameraSave;				   // size=0, offset=0
	long cameraRestore;				   // size=0, offset=0
	struct _BGObject *bgObject;		   // size=24, offset=0
	long value[2];					   // size=8, offset=0
	struct QUATG2_80fake sound;		   // size=12, offset=0
	void *intro;					   // size=0, offset=0
	long deathZ;					   // size=0, offset=0
	struct QUATG2_81fake dsignal;	  // size=8, offset=0
	void *mirror;					   // size=0, offset=0
	long fogNear;					   // size=0, offset=0
	long fogFar;					   // size=0, offset=0
	struct QUATG2_82fake gotoFrame;	// size=8, offset=0
	struct QUATG2_83fake changeModel;  // size=8, offset=0
	void *vmObject;					   // size=0, offset=0
	struct QUATG2_84fake logic;		   // size=8, offset=0
	void *callSignal;				   // size=0, offset=0
	struct _SVector offset;			   // size=8, offset=0
	struct Signal *gotoLabel;		   // size=0, offset=0
	struct Signal *gosubLabel;		   // size=0, offset=0
	struct QUATG2_85fake control;	  // size=8, offset=0
	struct QUATG2_86fake zSignal;	  // size=12, offset=0
	struct QUATG2_87fake StreamLevel;  // size=24, offset=0
	struct QUATG2_88fake shards;	   // size=12, offset=0
	struct QUATG2_89fake cameraSpline; // size=8, offset=0
	struct QUATG2_90fake screenWipe;   // size=4, offset=0
	long voiceSitId;				   // size=0, offset=0
	struct QUATG2_91fake introFX;	  // size=8, offset=0
	struct QUATG2_92fake introActive;  // size=8, offset=0
	struct QUATG2_93fake levelChange;  // size=18, offset=0
	long blendStart;				   // size=0, offset=0
	struct QUATG2_94fake setTimes;	 // size=8, offset=0
	struct QUATG2_95fake color;		   // size=4, offset=0
	struct QUATG2_96fake print;		   // size=12, offset=0
	long slideAngle;				   // size=0, offset=0
};

union QUATG2_98fake // Hashcode: 0x98B13AA6 (dec: -1733215578)
{
	struct _HSphere *hsphere; // size=20, offset=0
	struct _HBox *hbox;		  // size=28, offset=0
	struct _HFace *hface;	 // size=12, offset=0
};

union QUATG2_103fake // Hashcode: 0x91DA1217 (dec: -1847979497)
{
	struct _VMOffset moveOffsets;		// size=6, offset=0
	struct _VMColorOffset colorOffsets; // size=3, offset=0
};

extern void G2Quat_ToEuler(struct _G2Quat_Type *quat, struct _G2EulerAngles_Type *euler, int order); // 0x80095ED8

extern void G2EulerAngles_FromMatrix(struct _G2EulerAngles_Type *euler, struct _G2Matrix_Type *matrix, long order); // 0x80095F1C

#endif
