#ifndef TIMERG2_H
#define TIMERG2_H

struct TIMERG2_68fake // hashcode: 0xE2A43AB1 (dec: -492553551)
{
	unsigned long (*function)(); // size=0, offset=0 //  hashcode: 0x3F94445C (dec: 1066681436), parent name: 'TIMERG2_68fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *fnData;				 // size=0, offset=4 //  hashcode: 0xCE2EE6A2 (dec: -835787102), parent name: 'TIMERG2_68fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_69fake // hashcode: 0x95AB6F9C (dec: -1783926884)
{
	struct _G2SVector3_Type base;   // size=6, offset=0 //  hashcode: 0x134FD387 (dec: 323998599), parent name: 'TIMERG2_69fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2SVector3_Type offset; // size=6, offset=6 //  hashcode: 0xD679B74E (dec: -696666290), parent name: 'TIMERG2_69fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_70fake // hashcode: 0x38F2D3F9 (dec: 955438073)
{
	struct _G2Quat_Type src;  // size=8, offset=0 //  hashcode: 0xD1EC6509 (dec: -773036791), parent name: 'TIMERG2_70fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _G2Quat_Type dest; // size=8, offset=8 //  hashcode: 0x71187DE1 (dec: 1897430497), parent name: 'TIMERG2_70fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union TIMERG2_71fake // Hashcode: 0x8A15530F (dec: -1978313969)
{
	struct TIMERG2_68fake callback; // size=8, offset=0
	struct TIMERG2_69fake vector;   // size=12, offset=0
	struct TIMERG2_70fake quat;		// size=16, offset=0
};

union TIMERG2_72fake // Hashcode: 0xD9819D78 (dec: -645816968)
{
	long color;				// size=0, offset=0
	struct _RGBAColor rgba; // size=4, offset=0
};

union TIMERG2_73fake // Hashcode: 0xDA46BDA8 (dec: -632898136)
{
	long l;		// size=0, offset=0
	short s[2]; // size=4, offset=0
	char c[4];  // size=4, offset=0
};

struct TIMERG2_74fake // hashcode: 0xE0DBADE3 (dec: -522474013)
{
	union TIMERG2_73fake size; // size=4, offset=0 //  hashcode: 0xB6E4B019 (dec: -1226526695), parent name: 'TIMERG2_74fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_75fake // hashcode: 0xD58B1EFC (dec: -712302852)
{
	short x;				// size=0, offset=0 //  hashcode: 0xC531FE17 (dec: -986579433), parent name: 'TIMERG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;				// size=0, offset=2 //  hashcode: 0xDAA6C728 (dec: -626604248), parent name: 'TIMERG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;				// size=0, offset=4 //  hashcode: 0x1F0B0E5D (dec: 520818269), parent name: 'TIMERG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short zrot;				// size=0, offset=6 //  hashcode: 0xB2237105 (dec: -1306300155), parent name: 'TIMERG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector offset; // size=8, offset=8 //  hashcode: 0xBB65C6D9 (dec: -1150957863), parent name: 'TIMERG2_75fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_76fake // hashcode: 0xA85B7E69 (dec: -1470398871)
{
	long index; // size=0, offset=0 //  hashcode: 0xE2CDBAB3 (dec: -489833805), parent name: 'TIMERG2_76fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0x9C4A0898 (dec: -1672869736), parent name: 'TIMERG2_76fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_77fake // hashcode: 0xB766693F (dec: -1218025153)
{
	long index; // size=0, offset=0 //  hashcode: 0x7A4C8C37 (dec: 2051836983), parent name: 'TIMERG2_77fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0xE83F6CC5 (dec: -398496571), parent name: 'TIMERG2_77fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_78fake // hashcode: 0x47923057 (dec: 1200762967)
{
	long index; // size=0, offset=0 //  hashcode: 0xD72E3B82 (dec: -684835966), parent name: 'TIMERG2_78fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value; // size=0, offset=4 //  hashcode: 0xDB5E8E77 (dec: -614560137), parent name: 'TIMERG2_78fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_79fake // hashcode: 0x4A4D4B29 (dec: 1246579497)
{
	long time;  // size=0, offset=0 //  hashcode: 0xF97EAA41 (dec: -109139391), parent name: 'TIMERG2_79fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long scale; // size=0, offset=4 //  hashcode: 0xAF531290 (dec: -1353510256), parent name: 'TIMERG2_79fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_80fake // hashcode: 0x18DE0233 (dec: 417202739)
{
	long action;   // size=0, offset=0 //  hashcode: 0x81CB139A (dec: -2117397606), parent name: 'TIMERG2_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long value[2]; // size=8, offset=4 //  hashcode: 0xF8E80A93 (dec: -119010669), parent name: 'TIMERG2_80fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_81fake // hashcode: 0x109331B4 (dec: 278081972)
{
	void *intro; // size=0, offset=0 //  hashcode: 0xE2047C4E (dec: -503022514), parent name: 'TIMERG2_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *data;  // size=0, offset=4 //  hashcode: 0xDB69DA9A (dec: -613819750), parent name: 'TIMERG2_81fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_82fake // hashcode: 0x7602500F (dec: 1979863055)
{
	void *intro; // size=0, offset=0 //  hashcode: 0x532940C1 (dec: 1395212481), parent name: 'TIMERG2_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long frame;  // size=0, offset=4 //  hashcode: 0xD395C0D6 (dec: -745160490), parent name: 'TIMERG2_82fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_83fake // hashcode: 0x842EF867 (dec: -2077296537)
{
	void *intro; // size=0, offset=0 //  hashcode: 0xF5F92557 (dec: -168221353), parent name: 'TIMERG2_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long model;  // size=0, offset=4 //  hashcode: 0xA57176C3 (dec: -1519290685), parent name: 'TIMERG2_83fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_84fake // hashcode: 0x2D41D826 (dec: 759289894)
{
	unsigned char target;	 // size=0, offset=0 //  hashcode: 0xDC6ED668 (dec: -596715928), parent name: 'TIMERG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source1;	// size=0, offset=1 //  hashcode: 0x6C1358B7 (dec: 1813207223), parent name: 'TIMERG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char source2;	// size=0, offset=2 //  hashcode: 0x57DBB54B (dec: 1474016587), parent name: 'TIMERG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad;		  // size=0, offset=3 //  hashcode: 0xB78B20C0 (dec: -1215618880), parent name: 'TIMERG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0x9DC169DB (dec: -1648268837), parent name: 'TIMERG2_84fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_85fake // hashcode: 0xB96E6E2F (dec: -1183945169)
{
	long timer;  // size=0, offset=0 //  hashcode: 0x74BB1507 (dec: 1958417671), parent name: 'TIMERG2_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long action; // size=0, offset=4 //  hashcode: 0x0EF75FF1 (dec: 251092977), parent name: 'TIMERG2_85fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_86fake // hashcode: 0x0ACA382E (dec: 181024814)
{
	short index;					// size=0, offset=0 //  hashcode: 0x52FE2250 (dec: 1392386640), parent name: 'TIMERG2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short z;						// size=0, offset=2 //  hashcode: 0x230AB264 (dec: 587903588), parent name: 'TIMERG2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *upSignal;   // size=0, offset=4 //  hashcode: 0x75CE08DD (dec: 1976436957), parent name: 'TIMERG2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSignal *downSignal; // size=0, offset=8 //  hashcode: 0x5E944D3A (dec: 1586777402), parent name: 'TIMERG2_86fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_87fake // hashcode: 0x3A992490 (dec: 983114896)
{
	long currentnum; // size=0, offset=0 //  hashcode: 0x9259093A (dec: -1839658694), parent name: 'TIMERG2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long streamID;   // size=0, offset=4 //  hashcode: 0xA79823DE (dec: -1483201570), parent name: 'TIMERG2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char toname[16]; // size=16, offset=8 //  hashcode: 0x09A7796B (dec: 161970539), parent name: 'TIMERG2_87fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_88fake // hashcode: 0xA269244A (dec: -1570167734)
{
	char num;			   // size=0, offset=0 //  hashcode: 0xB2741C0E (dec: -1301013490), parent name: 'TIMERG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char vel;			   // size=0, offset=1 //  hashcode: 0x74B1B795 (dec: 1957803925), parent name: 'TIMERG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short misc;			   // size=0, offset=2 //  hashcode: 0xBBA3B58C (dec: -1146899060), parent name: 'TIMERG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char flags;			   // size=0, offset=4 //  hashcode: 0xBCE867AC (dec: -1125619796), parent name: 'TIMERG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char timeToLive;	   // size=0, offset=5 //  hashcode: 0x3C781B24 (dec: 1014504228), parent name: 'TIMERG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short dummy2;		   // size=0, offset=6 //  hashcode: 0xB16B0FC4 (dec: -1318383676), parent name: 'TIMERG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Object *object; // size=0, offset=8 //  hashcode: 0x81D4DB4E (dec: -2116756658), parent name: 'TIMERG2_88fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_89fake // hashcode: 0xB7C92561 (dec: -1211554463)
{
	long index;  // size=0, offset=0 //  hashcode: 0x79881B67 (dec: 2038963047), parent name: 'TIMERG2_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0x7DBEA880 (dec: 2109646976), parent name: 'TIMERG2_89fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_90fake // hashcode: 0xABBF21FE (dec: -1413537282)
{
	short type; // size=0, offset=0 //  hashcode: 0xE8286C09 (dec: -400004087), parent name: 'TIMERG2_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time; // size=0, offset=2 //  hashcode: 0x257E3C6F (dec: 629029999), parent name: 'TIMERG2_90fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_91fake // hashcode: 0xA328CA96 (dec: -1557607786)
{
	long time;   // size=0, offset=0 //  hashcode: 0x9DC4BDA1 (dec: -1648050783), parent name: 'TIMERG2_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	void *intro; // size=0, offset=4 //  hashcode: 0xEF86B39C (dec: -276384868), parent name: 'TIMERG2_91fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_92fake // hashcode: 0xBF19BC29 (dec: -1088832471)
{
	void *intro;			  // size=0, offset=0 //  hashcode: 0x92120560 (dec: -1844312736), parent name: 'TIMERG2_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct Signal *gotoLabel; // size=0, offset=4 //  hashcode: 0x6D035511 (dec: 1828934929), parent name: 'TIMERG2_92fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_93fake // hashcode: 0xBA4EFBDC (dec: -1169228836)
{
	char world[9]; // size=9, offset=0 //  hashcode: 0x146F62F9 (dec: 342844153), parent name: 'TIMERG2_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char level[9]; // size=9, offset=9 //  hashcode: 0x337D9DAC (dec: 863870380), parent name: 'TIMERG2_93fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_94fake // hashcode: 0x2421EE0C (dec: 606203404)
{
	struct Signal *signal; // size=0, offset=0 //  hashcode: 0x545669D9 (dec: 1414949337), parent name: 'TIMERG2_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long times;			   // size=0, offset=4 //  hashcode: 0xF2C0978E (dec: -222259314), parent name: 'TIMERG2_94fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_95fake // hashcode: 0xA707B269 (dec: -1492667799)
{
	unsigned char r;   // size=0, offset=0 //  hashcode: 0x6BCEA63E (dec: 1808705086), parent name: 'TIMERG2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char g;   // size=0, offset=1 //  hashcode: 0x71061B1A (dec: 1896225562), parent name: 'TIMERG2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char b;   // size=0, offset=2 //  hashcode: 0x9A643703 (dec: -1704708349), parent name: 'TIMERG2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	unsigned char pad; // size=0, offset=3 //  hashcode: 0xD533A6F9 (dec: -718035207), parent name: 'TIMERG2_95fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_96fake // hashcode: 0x066ADB31 (dec: 107666225)
{
	short x;	 // size=0, offset=0 //  hashcode: 0x9DC1846E (dec: -1648262034), parent name: 'TIMERG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short y;	 // size=0, offset=2 //  hashcode: 0x6C6DAF34 (dec: 1819127604), parent name: 'TIMERG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short time;  // size=0, offset=4 //  hashcode: 0x12BAE602 (dec: 314238466), parent name: 'TIMERG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short index; // size=0, offset=6 //  hashcode: 0x836ED717 (dec: -2089887977), parent name: 'TIMERG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	char *text;  // size=0, offset=8 //  hashcode: 0xC6FEA932 (dec: -956389070), parent name: 'TIMERG2_96fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

union TIMERG2_97fake // Hashcode: 0x50F2DB91 (dec: 1358093201)
{
	struct TIMERG2_74fake misc[3];		// size=12, offset=0
	struct _CameraKey *cameraKey;		// size=24, offset=0
	struct TIMERG2_75fake teleport;		// size=16, offset=0
	struct TIMERG2_76fake cameraValue;  // size=8, offset=0
	struct TIMERG2_77fake miscValue;	// size=8, offset=0
	struct TIMERG2_78fake logicValue;   // size=8, offset=0
	long timer;							// size=0, offset=0
	long times;							// size=0, offset=0
	long lightGroup;					// size=0, offset=0
	long farPlane;						// size=0, offset=0
	long cameraAdjust;					// size=0, offset=0
	long cameraMode;					// size=0, offset=0
	long cameraLock;					// size=0, offset=0
	long cameraUnlock;					// size=0, offset=0
	long cameraSmooth;					// size=0, offset=0
	long cameraTimer;					// size=0, offset=0
	struct TIMERG2_79fake cameraShake;  // size=8, offset=0
	long cameraSave;					// size=0, offset=0
	long cameraRestore;					// size=0, offset=0
	struct _BGObject *bgObject;			// size=24, offset=0
	long value[2];						// size=8, offset=0
	struct TIMERG2_80fake sound;		// size=12, offset=0
	void *intro;						// size=0, offset=0
	long deathZ;						// size=0, offset=0
	struct TIMERG2_81fake dsignal;		// size=8, offset=0
	void *mirror;						// size=0, offset=0
	long fogNear;						// size=0, offset=0
	long fogFar;						// size=0, offset=0
	struct TIMERG2_82fake gotoFrame;	// size=8, offset=0
	struct TIMERG2_83fake changeModel;  // size=8, offset=0
	void *vmObject;						// size=0, offset=0
	struct TIMERG2_84fake logic;		// size=8, offset=0
	void *callSignal;					// size=0, offset=0
	struct _SVector offset;				// size=8, offset=0
	struct Signal *gotoLabel;			// size=0, offset=0
	struct Signal *gosubLabel;			// size=0, offset=0
	struct TIMERG2_85fake control;		// size=8, offset=0
	struct TIMERG2_86fake zSignal;		// size=12, offset=0
	struct TIMERG2_87fake StreamLevel;  // size=24, offset=0
	struct TIMERG2_88fake shards;		// size=12, offset=0
	struct TIMERG2_89fake cameraSpline; // size=8, offset=0
	struct TIMERG2_90fake screenWipe;   // size=4, offset=0
	long voiceSitId;					// size=0, offset=0
	struct TIMERG2_91fake introFX;		// size=8, offset=0
	struct TIMERG2_92fake introActive;  // size=8, offset=0
	struct TIMERG2_93fake levelChange;  // size=18, offset=0
	long blendStart;					// size=0, offset=0
	struct TIMERG2_94fake setTimes;		// size=8, offset=0
	struct TIMERG2_95fake color;		// size=4, offset=0
	struct TIMERG2_96fake print;		// size=12, offset=0
	long slideAngle;					// size=0, offset=0
};

union TIMERG2_98fake // Hashcode: 0x58BBB05C (dec: 1488695388)
{
	struct _HSphere *hsphere; // size=20, offset=0
	struct _HBox *hbox;		  // size=28, offset=0
	struct _HFace *hface;	 // size=12, offset=0
};

union TIMERG2_103fake // Hashcode: 0xA887FA09 (dec: -1467483639)
{
	struct _VMOffset moveOffsets;		// size=6, offset=0
	struct _VMColorOffset colorOffsets; // size=3, offset=0
};

struct TIMERG2_105fake // hashcode: 0xE49BBFD5 (dec: -459554859)
{
	struct MultiSpline *posSpline;	// size=0, offset=0 //  hashcode: 0xE1B1BE08 (dec: -508445176), parent name: 'TIMERG2_105fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct MultiSpline *targetSpline; // size=0, offset=4 //  hashcode: 0xA9655A76 (dec: -1452975498), parent name: 'TIMERG2_105fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector lastSplinePos;	// size=8, offset=8 //  hashcode: 0x0C9A0C4C (dec: 211422284), parent name: 'TIMERG2_105fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short splinePointAhead;			  // size=0, offset=16 //  hashcode: 0xBAFC637E (dec: -1157864578), parent name: 'TIMERG2_105fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	short cinema_done;				  // size=0, offset=18 //  hashcode: 0x799CFAB7 (dec: 2040330935), parent name: 'TIMERG2_105fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	int splinecam_currkey;			  // size=0, offset=20 //  hashcode: 0x096EAC67 (dec: 158248039), parent name: 'TIMERG2_105fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	int splinecam_helpkey;			  // size=0, offset=24 //  hashcode: 0x32D38579 (dec: 852723065), parent name: 'TIMERG2_105fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_106fake // hashcode: 0x5264044B (dec: 1382286411)
{
	struct _Position offset;   // size=6, offset=0 //  hashcode: 0xE9551662 (dec: -380299678), parent name: 'TIMERG2_106fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _Rotation rotation; // size=8, offset=6 //  hashcode: 0x23BC028A (dec: 599523978), parent name: 'TIMERG2_106fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long focusDistance;		   // size=0, offset=16 //  hashcode: 0xE8C29033 (dec: -389902285), parent name: 'TIMERG2_106fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_107fake // hashcode: 0x9D7434F8 (dec: -1653328648)
{
	struct _TFace *tface;				 // size=12, offset=0 //  hashcode: 0xD9040B6A (dec: -654046358), parent name: 'TIMERG2_107fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *oldTFace;			 // size=12, offset=4 //  hashcode: 0xF451F3C5 (dec: -195955771), parent name: 'TIMERG2_107fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector oldTargetRot;		 // size=8, offset=8 //  hashcode: 0x2867A321 (dec: 677880609), parent name: 'TIMERG2_107fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long timer;							 // size=0, offset=16 //  hashcode: 0xC4357564 (dec: -1003129500), parent name: 'TIMERG2_107fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _SVector oldFocusInstancePos; // size=8, offset=20 //  hashcode: 0x061A773E (dec: 102397758), parent name: 'TIMERG2_107fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_108fake // hashcode: 0xF177B353 (dec: -243813549)
{
	long stopTimer;			 // size=0, offset=0 //  hashcode: 0x827E5883 (dec: -2105649021), parent name: 'TIMERG2_108fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long stopHit;			 // size=0, offset=4 //  hashcode: 0x39E83640 (dec: 971519552), parent name: 'TIMERG2_108fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *tface;	// size=12, offset=8 //  hashcode: 0x2F6B69FF (dec: 795568639), parent name: 'TIMERG2_108fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct _TFace *oldTFace; // size=12, offset=12 //  hashcode: 0xB798D41C (dec: -1214720996), parent name: 'TIMERG2_108fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	long hit;				 // size=0, offset=16 //  hashcode: 0x41EF0470 (dec: 1106183280), parent name: 'TIMERG2_108fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

struct TIMERG2_109fake // hashcode: 0xDA8B298B (dec: -628414069)
{
	struct TIMERG2_105fake Cinematic; // size=28, offset=0 //  hashcode: 0x1D82642E (dec: 495084590), parent name: 'TIMERG2_109fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct TIMERG2_106fake Idle;	  // size=20, offset=28 //  hashcode: 0x3A86E41B (dec: 981918747), parent name: 'TIMERG2_109fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct TIMERG2_107fake Behind;	// size=28, offset=48 //  hashcode: 0x9835B8BF (dec: -1741309761), parent name: 'TIMERG2_109fake', parent hashcode: 0xFFFFFFFF (dec: -1)
	struct TIMERG2_108fake Follow;	// size=20, offset=76 //  hashcode: 0x8DED92C2 (dec: -1913810238), parent name: 'TIMERG2_109fake', parent hashcode: 0xFFFFFFFF (dec: -1)
};

extern short G2Timer_GetFrameTime(); // 0x80096280

#endif
